nome: CI



em: [push, workflow_dispatch]



empregos:

  construir:



    run-on: windows-latest



    degraus:

    - nome: Baixar

      execute: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - nome: Extrato

      executar: Expand-Archive ngrok.zip

    - nome: Auth

      execute: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      ambiente:

        NGROK_AUTH_TOKEN: ${{ segredos.NGROK_AUTH_TOKEN }}

    - nome: Ativar TS

      execute: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

    - execute: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - execute: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Create Tunnel

      run: .\ngrok\ngrok.exe tcp 3389
